# Generated by Django 2.1.2 on 2018-10-21 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181021_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='progress_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='progress_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
